#!/bin/bash
title="Fish Shell Setup"
description="- Installs Fish shell and related tools"
status=off

main() {
    # 
    commandFailure="Fish shell installation has failed."

    # Fish Shell
    echo -e "Installing Fish shell... \n"
    xbps-install -Sy -R $installRepo -r /mnt fish || failureCheck
    echo -e "Fish shell has been installed. \n"

    # Fish shell
    echo -e "Setting Fish as the default shell... \n"
    chroot /mnt /bin/bash -c "chsh -s /usr/bin/fish" || failureCheck
    echo -e "Fish shell is now the default shell. \n"

    # Oh My Fish
    echo -e "Installing Oh My Fish... \n"
    chroot /mnt /bin/bash -c "curl -L https://get.oh-my.fish | fish" || failureCheck
    echo -e "Oh My Fish has been installed. \n"

    # Fish
    echo -e "Installing useful Fish plugins... \n"
    chroot /mnt /usr/bin/fish -c "omf install bass" || failureCheck
    chroot /mnt /usr/bin/fish -c "omf install pj" || failureCheck
    chroot /mnt /usr/bin/fish -c "omf install git" || failureCheck
    echo -e "Fish plugins have been installed. \n"

    # Fish
    echo -e "Configuring Fish shell environment... \n"
    mkdir -p /mnt/home/$USER/.config/fish || failureCheck
    echo "set PATH /usr/local/bin /usr/bin /bin /usr/sbin /sbin" > /mnt/home/$USER/.config/fish/config.fish || failureCheck
    echo -e "Fish shell environment has been configured. \n"

    return 0
}
