#!/bin/bash
title=noto-fonts
description="- Noto TTF fonts typically used by websites"
status=on

main() {
    install noto-fonts-ttf noto-fonts-cjk ||
        { commandFailure="Noto TTF fonts installation has failed." ; die ; }

    return 0
}
